# Generated by Django 4.2.6 on 2023-10-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="categorie",
            field=models.TextField(default="biologie"),
            preserve_default=False,
        ),
    ]
