# Generated by Django 4.2.4 on 2023-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publicite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                ("lien", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="publicites/photos/"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modification", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
