# Generated by Django 4.2.6 on 2023-10-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="evernements/pdfs/"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="evernements/photos/"
                    ),
                ),
                ("date_debut", models.DateTimeField(auto_now_add=True, null=True)),
                ("ate_fin", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
