# Generated by Django 4.2.6 on 2023-10-28 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Evernements", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evenement",
            old_name="ate_fin",
            new_name="date_fin",
        ),
    ]
