# Generated by Django 4.2.6 on 2023-10-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Evernements", "0002_rename_ate_fin_evenement_date_fin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="date_debut",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date_fin",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="evenements/photos/"
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="evenements/pdfs/"
            ),
        ),
    ]
